account/urls.py
from django.urls import re_path as url
from . import views
from django.contrib.auth.decorators import login_required
from django.contrib.auth import views as auth

app_name = 'accounts'
urlpatterns = [
    url(r'^register/$', views.register, name='register'),
    url(r'^profile/(?P<user>[.\-\w]+)$', views.profile, name='profile'),
    url(r'^login/$', views.login_user, name='login'),
    url(r'^logout/$', views.logout_user, name='logout'),
    url(r'^update-profile/(?P<user>[.\-\w]+)/$', views.update_profile, name='update_profile'),
    url(r'all-questions/(?P<user>[.\-\w]+)/$', views.all, name='all'),
    url(r'all-answers/(?P<user>[.\-\w]+)/$', views.all2, name='all2')



]

classk/urls.py
from django.urls import re_path as url
from django.urls import include
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from main.views import QuestionSitemap

sitemaps = {
    'question': QuestionSitemap,
}

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('main.urls')),
    url(r'^accounts/', include('account.urls')),
    url(r'sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
     name='django.contrib.sitemaps.views.sitemap')
    
]

main/urls.py
from django.urls import re_path as url
from . import views

app_name = 'main'

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'ask-question/$', views.question, name='ask-question'),
    url(r'^details/(?P<slug>[.\-\w]+)$', views.details, name='details'),
    url(r'^delete/(?P<slug>[.\-\w]+)/$', views.delete, name='delete'),
    url(r'^edit/(?P<slug>[.\-\w]+)/$', views.edit_details, name='edit'),
    url(r'^answer/update/(?P<slug>[.\-\w]+)/(?P<id>\d+)/$', views.update_answer, name='update_answer'),
    url(r'^answer/delete/(?P<slug>[.\-\w]+)/(?P<id>\d+)/$', views.delete_answer, name='delete_answer'),
    url(r'^questions/filter/(?P<tag>[.\-\w]+)/$', views.filter_types, name='filter'),
    url(r'^website-tutorial/$', views.tutorial, name='tutorial'),
    url(r'^request/topic/$', views.request_topic, name='request_topic'),
    url(r'^display/requests/$', views.display_request, name='display_request'),
    url(r'^details/(?P<slug>[.\-\w]+)/(?P<id>\d+)/satisfied/$', views.satisfied, name='satisfied'),
    url(r'^details/(?P<slug>[.\-\w]+)/(?P<id>\d+)/irrelevant/$', views.out_of_context, name='irrelevant'),
    url(r'^delete/topic/(?P<id>\d+)/$', views.delete_topics, name='delete_topics'),
    url(r'^add-category/$', views.add_categorys, name='add-category'),
    url(r'^details/(?P<slug>[.\-\w]+)/(?P<id>\d+)/undo-satisfied/$', views.undo_satisfied, name='undo_satisfied'),
    url(r'^details/(?P<slug>[.\-\w]+)/(?P<id>\d+)/undo-irrelevant/$', views.undo_out_of_context, name='undo_irrelevant'),
    url(r'^satisfied/answers/all/$', views.all_satisfied, name='all_satisfied'),
    url(r'no-results/all/$', views.no_results, name='no_results'),
    url(r'^google1178e9883bf5717c\.html/$', views.google, name='google'),
    url(r'^contact/$', views.contact, name='contact'),
    url(r'^see-contacts/$', views.contact_view, name='contact_view')
]

main/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify
import datetime
from django.utils import timezone

# Create your models here.
class Category(models.Model):
    category = models.CharField(max_length=50)

    def __str__(self):
        return self.category

class Question(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=150, default=None)
    description = models.TextField(max_length=3000)
    slug = models.SlugField(max_length=140, unique=True)
    date = models.DateTimeField(null=True, default=timezone.now())
    category = models.ForeignKey(Category, null=True, default=None, on_delete=models.CASCADE)
    satisfied = models.BooleanField(default=False)
    viewed = models.IntegerField(default=0)
    
    def __str__(self):
        return self.title

    def _get_unique_slug(self):
        slug = slugify(self.title)
        unique_slug = slug
        num = 1
        while Question.objects.filter(slug=unique_slug).exists():
            unique_slug = '{}-{}'.format(slug, num)
            num += 1
        return unique_slug

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = self._get_unique_slug()
        super().save()

    # for sitemaps
    def get_absolute_url(self):
        return '/details/%s' %self.slug

class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    user = models.ForeignKey(User, default=None, on_delete=models.CASCADE)
    answer = models.TextField(max_length=3000, null=True)
    posted_on = models.DateField(default=datetime.datetime.now().date())
    satisfied = models.BooleanField(default=False)
    irrelevant = models.BooleanField(default=False)

    def __str__(self):
        return self.question.title


# request topics
class Topic(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100, null=True)
    description = models.TextField(max_length=500, null=True)
    date = models.DateField(auto_now_add = True, null=True)


    def __str__(self):
        return self.title

# notifications
class Notification(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE, null=True)
    answer = models.ForeignKey(Answer, on_delete=models.CASCADE, null=True)
    any_message = models.CharField(max_length=500, null=True, default="Notification")
    date = models.DateField(default=timezone.now())
    read = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

class Contact(models.Model):
    name = models.CharField(max_length=150)
    email = models.EmailField(max_length=150)
    message = models.TextField(max_length=500)
    date = models.DateTimeField(default=timezone.now())
    def __str__(self):
        return self.name

main/forms.py
from django import forms
from .models import *

class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ('category','title', 'description',)

class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ('answer',)

class TopicForm(forms.ModelForm):
    title = forms.CharField(max_length=80, required=True)
    class Meta:
        model = Topic
        fields = ('title', 'description')

class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ('category',)

class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ('email', 'name', 'message')

main/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import Http404, HttpResponseRedirect, HttpResponse
from .models import *
import datetime
from .forms import *
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from collections import Counter
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Count
from django.utils import timezone
from account.models import Profile
from django.core.exceptions import ObjectDoesNotExist
from django.db.models import Max
from datetime import date
from django.db.models import Q
from django.contrib.sitemaps import Sitemap
import time
# Create your views here.
trend_counter= []
def home(request):
    questions = Question.objects.all().order_by("-date")
    if request.user.is_authenticated:
        notifications = Notification.objects.filter(user=request.user, read=False)
        notif_counts = notifications.count()

        # points
        points = Profile.objects.get(user=request.user)
        score = points.points
    else:
        notifications = 'None'
        notif_counts = 0

        points = 'None'
        score = 0
    # counting answers on specific questions
    results = Question.objects.annotate(num_answers=Count('answer')).order_by("-date")

    # categories
    categories = Category.objects.all().order_by('category')
    # PAGINATION ===============================
    page = request.GET.get('page', 1)

    paginator = Paginator(results,10)
    try:
        results = paginator.page(page)
    except PageNotAnInteger:
        results = paginator.page(1)
    except EmptyPage:
        results = paginator.page(paginator.num_pages)
   
    # trending question
    trending_question = Question.objects.all()
    for t in trending_question:
        po = t.viewed
        trend_counter.append(po)
    new_trend = sorted(trend_counter)
    trend = None
    try:
        trend_index = new_trend[len(new_trend)-1]
        trend = Question.objects.get(viewed=trend_index)
    except:
        pass
    # points of the users
    # search the questions ============
    query= request.GET.get("q")
    if query:
        short_list = Question.objects.all()
        questions = short_list.filter(Q(title__icontains=query) | Q(category__category__icontains=query) | Q(user__username__icontains=query))
        resulted = questions.annotate(num_answers=Count('answer'))
        counted = questions.count()
        context1 = {
            'questions': questions,
            'query': query,
            'counted': counted,
            'resulted': resulted,
        }
        return render(request, 'main/search.html',context1)
    context = {
        'questions': questions,
        'trend': trend,
        'results': results,
        'notifications':notifications,
        'notif_counts':notif_counts,
        'categories':categories,
        'score':score,
        'points':points,
    }
    return render(request, 'main/index.html', context)

# ask questions
@login_required(redirect_field_name='classk_redirect')
def question(request):
    if request.user.is_authenticated:
        # points
        points = Profile.objects.get(user=request.user)
        score = points.points
        lists = Category.objects.all().order_by("category")
        if request.method == 'POST':
            title = request.POST.get('title')
            if not title:
                raise ValueError('Please add a suitable title.')
            description = request.POST.get('description')
            user = request.user
            date =  timezone.now()
            vl = request.POST.get('values')
            category_item = Category.objects.get(category=vl)
            questionobj = Question(user=user, title=title, description=description, date=date, category=category_item)
            questionobj.save()
            return redirect('main:home')
        else:
            form = QuestionForm()
        return render(request, 'main/ask-question.html', {'form': form,'lists':lists, 'points':points, 'score':score})
    else:
        return redirect('accounts:login')
# details for the question
def details(request, slug):
    # setting notifications for the page
    if request.user.is_authenticated:
        notifications = Notification.objects.filter(user=request.user, read=False)
        notif_counts = notifications.count()

        # points
        points = Profile.objects.get(user=request.user)
        score = points.points
    else:
        notifications = 'None'
        notif_counts = 0

        points = 'None'
        score = 0
    # getting the details of the question   
    question = Question.objects.get(slug=slug)
    answers = Answer.objects.filter(question_id=question.id)
    cot = answers.count()
    # similar questions
    similar = Question.objects.filter(category=question.category)
    final = similar.exclude(title=question.title).order_by('-date')[:5]

    # adding the views
    initial_views = 0
    question.viewed = int(question.viewed) + 1
    question.save()
    
    viewed = question.viewed
    # questions by that user
    questions_by_the_user = Question.objects.filter(user=question.user).count()

    # answers with mark satisfied
    satisfied_answers = Answer.objects.filter(question_id = question.id, satisfied=True)
    no_review_answers = Answer.objects.filter(question_id=question.id, satisfied=False)

    # categories
    cats = Category.objects.all()[:5]

    # if answer form is submitted
    form = AnswerForm(request.POST or None)
    if request.method =='POST':
        form = AnswerForm(request.POST or None)
        if form.is_valid():
            details = form.save(commit=False)
            details.question_id = question.id
            details.user = request.user
            details.save()
            n = Notification(user=question.user, question=question, any_message='Your Question has been answered.')
            n.save()
            return HttpResponseRedirect('/details/%s' %slug)

    # notifications
    if request.user.is_authenticated:
        notification = Notification.objects.filter(user=request.user, read=False)
        for n in notification:
            if n.question.slug == slug:
                n.read = True
                n.save()
        
    context = {
        'question': question,
        'answers':answers,
        'cot': cot,
        'final': final,
        'questions_by_the_user': questions_by_the_user,
        'viewed': viewed,
        'satisfied_answers': satisfied_answers,
        'no_review_answers': no_review_answers,
        'cats':cats,
        'notifications': notifications,
        'notif_counts':notif_counts,
        'points': points,
        'score':score,
        'form': form
    }
    return render(request, 'main/detail.html', context)

# delete question
def delete(request, slug):
    if request.user.is_authenticated:
        instance = get_object_or_404(Question, slug=slug)
        if request.user == instance.user:
            instance.delete()
            messages.success(request, 'Question Deleted Successfully!')  # <-
            return redirect('main:home')
        else:
            return redirect('main:home')

# edit question
def edit_details(request, slug):
    if request.user.is_authenticated:
        question = Question.objects.get(slug=slug)
        if request.user == question.user:
            if request.method == 'POST':
                form = QuestionForm(request.POST, instance=question)
                if form.is_valid():
                    form.save()
                    messages.success(request, 'Question Edited Successfully!')  # <-
                    return HttpResponseRedirect('/details/%s' %slug)
            else:
                form = QuestionForm(instance=question)
            template = 'main/edit-question.html'
            context = {'form': form}
            return render(request, template, context)
        else:
            return redirect("main:home")
    else:
        return redirect("main:home")


# update answer
def update_answer(request, slug, id):
    # test user login here
    if request.user.is_authenticated:
        quest = Question.objects.get(slug=slug)
        try:
            answer = Answer.objects.get(user=request.user, question_id=quest.id, id=id)
        except:
            return redirect("main:home")
        answer = Answer.objects.get(user=request.user, question_id=quest.id, id=id)
        new = (answer.answer)
        if request.user == answer.user:
            if request.method == 'POST':
                form = AnswerForm(request.POST or None, instance=answer)
                if form.is_valid():
                    form.save()
                    return HttpResponseRedirect('/details/%s' %slug)
            else:
                form = AnswerForm(request.POST or None, instance=answer)
            return render(request, 'main/edit-answer.html', {'form': form, 'quest':quest})
        else:
            return redirect("main:home")

    else:
        return redirect("main:home")

# delete answer by the user
def delete_answer(request, slug, id):
    if request.user.is_authenticated:
        quest = Question.objects.get(slug=slug)
        try:
            answer = Answer.objects.get(user=request.user, question_id=quest.id, id=id)
        except:
            return redirect("main:home")
        if request.user == answer.user:
            if not answer.satisfied == True:
                answer.delete()
                messages.success(request, 'Answer Deleted Successfully!')
                return HttpResponseRedirect('/details/%s' %slug)
            else:
                return HttpResponseRedirect('/details/%s' %slug)
        else:
            return HttpResponseRedirect('/details/%s' %slug)



    else:
        return redirect("accounts:login")

def filter_types(request, tag):
    filters = Category.objects.get(category=tag)
    questions = Question.objects.filter(category=filters)[:1]

main/templates/main/detail.html
{% extends 'main/base.html' %}

{% block title %}
    {{ question.category }} - {{ question.title }}
{% endblock %}

{% load crispy_forms_tags %} {% block content %}

<div class="container">
    <div class="row">
        <div class="col-md-10">
            <br>
            <h1 id="titleq">{{ question.title }}</h1>
            {% if question.user == request.user %}
            <a href="{% url 'main:edit' question.slug %}" data-toggle="tooltip" data-placement="top" title="Edit Question">
                <i class="fas fa-pencil-alt"></i>
            </a>&nbsp;&nbsp;
            <a onclick="return confirm('Are you sure you want to delete this question?')" href="{% url 'main:delete' question.slug %}"
                data-toggle="tooltip" data-placement="top" title="Delete Question">
                <i class="fas fa-trash"></i>
            </a>
            {% else %} {% endif %}
            <br>
            <div class="social-media-links" style="padding:10px;">
                <a href="http://www.facebook.com/sharer/sharer.php?u=http://classk.herokuapp.com{{ request.get_full_path|urlencode }}" target="_blank"> <i class="fab fa-facebook-square"></i> </a>
                &nbsp;&nbsp;<a href="https://twitter.com/home?status=https://classk.heokuapp.com{{ request.get_full_path|urlencode }}" target="_blank"> <i class="fab fa-twitter"></i>  </a>
                &nbsp;&nbsp; <a href="https://plus.google.com/share?url=http://classk.herokuapp.com{{ request.get_full_path|urlencode }}" target="_blank"> <i class="fab fa-google-plus-g"></i> </a>
            </div>
            <i>Viewed: {{ viewed }} times.</i>
            <p>{{ question.date }}</p>

        </div>
    </div>
    <div class="row">
        <div class="col-md-9">
            <p>{{ question.description }}</p>
        </div>
        <div class="col-md-3">
            <div class="box">
                <a href="{% url 'main:filter' question.category %}">
                    <p class="badge text-white" style="background:#122f40;">{{ question.category }}</p>
                </a>
                <br> Posted By:
                <i class="fas fa-user"></i>
                <a href="{% url 'accounts:profile' question.user %}" id="links">{{ question.user|upper }}</a>({{questions_by_the_user}})
            </div>
        </div>
    </div>
    <hr>

        <br>

    <br>
    <h3 class="text-left" id="titleq">Answers: {{ cot }}</h3>

    <div class="row">
        <div class="col-md-9">
            {% for a in answers %}
            <div class="answers">
                <a href="{% url 'accounts:profile' a.user %}" class="text-right" id="links">{{ a.user }}</a>
                <p>{{ a.posted_on }}</p>
                <p id="titleq">{{ a.answer|linebreaks }}</p>
                <!-- satisfied answer label -->
                {% if a.satisfied %}
                <p class="badge badge-success">Marked Satisfied</p>
                {% if request.user == question.user %}
                <a href="{% url 'main:undo_satisfied' slug=question.slug id=a.id%}" id="undo">
                    <i class="fas fa-undo"></i>
                </a>
                {% endif %} {% else %}

                <!-- irrelevant -->
                {% if a.irrelevant %}
                <p class="badge badge-danger">Marked Irrelevant</p>
                {% if request.user == question.user %}
                <a href="{% url 'main:undo_irrelevant' slug=question.slug id=a.id%}" data-toggle="tooltip" data-placement="top" title="Undo">
                    <i class="fas fa-undo"></i>
                </a>
                {% endif %} {% endif %} {% if request.user == question.user %} {% if not a.satisfied %} {% if not a.irrelevant %}
                <div style="font-size:20px;">
                    <a href="{% url 'main:satisfied' slug=question.slug id=a.id%}" data-toggle="tooltip" data-placement="top" title="Satisfied">
                        <i class="fas fa-check"></i>
                    </a> &nbsp;&nbsp;
                    <a href="{% url 'main:irrelevant' slug=question.slug id=a.id%}" data-toggle="tooltip" data-placement="top" title="Irrelevant">
                        <i class="fas fa-times"></i>
                    </a>
                </div>
                {%endif %} {% endif %}{% else %} {% endif %} {% endif %}
                <!-- end of satisfied answer label -->
                {% if a.user == request.user %} {% if not a.satisfied %}
                <a href="{% url 'main:update_answer' slug=question.slug id=a.id %}" class="btn btn-sm btn-warning">Edit Answer</a>
                <a href="{% url 'main:delete_answer' slug=question.slug id=a.id%}" class="btn btn-sm btn-danger">Delete Answer</a>
                {% endif %} {% else %} {% endif %}
                <!-- form for the satisfaction indicator -->

                <!-- end of satisfaction form -->
            </div>
            <br> {% endfor %}
            <h3>Post Your Own Answer</h3>
            {% if request.user.is_authenticated %}
            <form action="" method="post" id="post-form">
                {% csrf_token %} {{form |crispy}}
                <input type="submit" value="Add Answer" class="btn btn-md btn-warning">
            </form>
            {% else %}
                <a href="{% url 'accounts:login' %}?next=/details/{{question.slug}}" class="btn btn-md btn-danger">Add Answer</a>
                <br>
                <br>
            {% endif %}
        </div>
        <div class="col-md-3">
            <div style="background-color:white; padding:10px;">
                <h3>Similar Questions</h3>
                <ul>
                    {% if final %} {% for f in final %}
                    <a href="{% url 'main:details' f.slug %}" id="links">
                        <li style="list-style-type:none;">{{ f.title }}</li>
                    </a>
                    {% endfor %} {% else %}
                    <p class="lead">No similar questions</p>
                    {% endif %}
                </ul>
                <br>
                <a href="{% url 'main:ask-question' %}" class="btn btn-md btn-primary">Ask a Question</a>
            </div>
            <br>
        </div>
    </div>
  
</div>

<script type="text/javascript">
    var frm = $('#post-form');
    frm.submit(function () {
        $.ajax({
            type: frm.attr('method'),
            url: frm.attr('action'),
            data: frm.serialize(),
            success: function (data) {
                console.log("Success");
            },
            error: function(data) {
                console.log("Error");
            }
        });
        return false;
    });
</script>

{% endblock %}

main/templates/main/filtered.html
{% extends 'main/base.html' %} 

{% block title %}
    {% for filter in questions %}
    {{ filter.category }}- All Questions
    {% endfor %}
{% endblock %}

{% block content %} {% for s in questions %}
<h1 class="text-center display-4">{{ s.category }}</h1>
<div class="container-fluid">
    <div class="row">
        {% endfor %} {% if questions_all %}
        <!-- second loop to get the contents -->
        <!-- a new column -->
        <div class="col-md-3">
            <div class="stats">
                {% for t in questions %}
                <h4>Questions in {{ t.category }}: {{ count_in_category }}</h4>
                {% endfor %}
            </div>
        </div>
        <!-- end of column -->
        <div class="col-md-8">
            <div id="qtns">
                {% for qs in questions_all %}
                <a href="{% url 'main:details' qs.slug %}" id="questions">
                    <h4 id="titleq">{{ qs.title }}</h4>
                </a>
                {% if qs.satisfied %}
                <i data-toggle="tooltip" data-placement="top" title="Marked Satisfied by the owner of the question." class="fas fa-check"
                    style="color:green;"></i>
                {% else %}
                <i>No results yet</i>
                {% endif %}
                <p class="badge" style="background:#122f40; color:white;">{{ qs.category }}</p>
                <p id="titleq">{{ qs.date }}
                    <a href="{% url 'accounts:profile' qs.user %}" id="questions-user-link">{{ qs.user }}</a>
                </p>
                <i>Viewed: {{ qs.viewed }} times.</i>

                <hr> {% endfor %}
            </div>
            <br> {% else %}
            <div class="conatiner text-center">
                <img class="img-fluid" src="https://www.dailydot.com/wp-content/uploads/e52/31/87610fa1a0ae891d.png" alt="No posts yet"  >
            <br> <br>
                <a href="{% url 'main:ask-question' %}" class="btn btn-lg btn-danger">Ask Question</a>
            </div>
            <br>
            <br> {% endif %}
        </div>

    </div>
</div>
{% endblock %}

main/templates/main/google1178e9883bf5717c.html
google-site-verification: google1178e9883bf5717c.html

main/templates/main/index.html
{% extends 'main/base.html' %} {% block title %} Ask Everything {% endblock %} {% block content %}


<!-- end of the message container -->
<!-- start of the actual questions -->
<div class="container-fluid">
    <hr>
    <a href="{% url 'main:all_satisfied' %}" id="trend_links">#All Satisfied Questions</a>&nbsp;&nbsp;
    <a href="{% url 'main:no_results' %}" id="trend_links">#No Results Questions</a>&nbsp;&nbsp;
    <hr>
    <div class="row">
        <!-- trending column -->

        <div class="col-md-3 col-sm-12">

            {% if not user.is_authenticated %}
            <div class="text-center">
                <a href="{% url 'accounts:login' %}?next={% url 'main:ask-question' %}" class="btn btn-lg btn-info">Ask Question</a>
            </div>
            <br> {% else %}
            <div class="text-center">
                <a href="{% url 'main:ask-question' %}" class="btn btn-lg btn-warning">Ask Quesiton</a>
            </div>
            <br> {% endif %}
            <div id="qtns1">

                <div class="qtns2">
                    Trending Question:
                    <a href="{% url 'main:details' trend.slug %}" id="trend_links">
                        <p>{{ trend }}</a> -
                    <i class="fas fa-user-circle"></i>
                    <i>{{ trend.user }}</i>
                    </p>
                    <p>
                        <i>Posted On: </i>{{ trend.date}}</p>
                </div>
                <br>
                <p class="text-center">
                    <i class="fas fa-trophy" style="color:#f1b838;"> </i>&nbsp;
                    <a href="#" id="links" style="color:white;">Hall Of Fame</a>&nbsp;
                    <i class="fas fa-trophy" style="color:#f1b838;"> </i>

                </p>
                <!-- all categories -->
                <h4 class="text-white">All Categories</h4>
                {% for c in categories %}
                <a href="{% url 'main:filter' tag=c.category %}">
                    <p class="badge badge-info">{{ c.category }}</p>
                </a>
                {% endfor %}
                <!-- end all categories -->
            </div>
            <br>
            <!-- ad -->
            <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
            <ins class="adsbygoogle" style="display:block; text-align:center;" data-ad-layout="in-article" data-ad-format="fluid" data-ad-client="ca-pub-9886177219084453"
                data-ad-slot="6421665636"></ins>
            <script>
                (adsbygoogle = window.adsbygoogle || []).push({});
            </script>
            <!-- end ad -->
        </div>
        <!-- end of trending column -->
        <div class="col-md-9 col-sm-12">
            <h1 class="text-left" id="brand"> Recently Added Questions</h1>
            <div id="qtns">
                {% for q in results %}
                <a href="{% url 'main:details' q.slug %}" id="questions">
                    <h4 id="titleq">{{ q.title }}</h4>
                    {% if q.satisfied %}
                    <i data-toggle="tooltip" data-placement="top" title="Marked Satisfied by the owner of the question." class="fas fa-check"
                        style="color:green;"></i>
                    {% else %}
                    <i>No results yet</i>
                    {% endif %}
                </a>
                <a href="{% url 'main:filter' q.category %}">
                    <p class="badge" style="background:#003346; color:white;">{{ q.category }}</p>
                </a>
                <p id="titleq">{{ q.date |timesince }} ago.
                    <a href="{% url 'accounts:profile' q.user %}" id="questions-user-link">{{ q.user }}</a>
                </p>
                <div class="text-right">
                    <i>Viewed: {{ q.viewed }} times.</i>
                    <p>Answers: {{q.num_answers}}</p>
                </div>
                <hr> {% endfor %}
            </div>
            <br>
            <div class="container">
                <div class="text-right">
                    <!-- pagination for the limited display of questions -->
                    <nav aria-label='pagination'>
                        {% if results.has_other_pages %}
                        <ul class="pagination">
                            {% if results.has_previous %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{ results.previous_page_number }}">&laquo;</a>
                            </li>
                            {% else %}
                            <li class="page-item disabled">
                                <span class="page-link">&laquo;</span>
                            </li>
                            {% endif %} {% for i in results.paginator.page_range %} {% if results.number == i %}
                            <li class=" page-item active">
                                <span class="page-link">{{ i }}
                                    <span class="sr-only">(current)</span>
                                </span>
                            </li>
                            {% else %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{ i }}">{{ i }}</a>
                            </li>
                            {% endif %} {% endfor %} {% if questions.has_next %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{ results.next_page_number }}">&raquo;</a>
                            </li>
                            {% else %}
                            <li class=" page-item disabled">
                                <span class="page-link">&raquo;</span>
                            </li>
                            {% endif %}
                        </ul>
                    </nav>
                    {% endif %}
                </div>
            </div>

        </div>
        <!-- end of the column div -->
    </div>
</div>

 {% endblock %}